export OJDBC_HOSTNAME=localhost
export OJDBC_PORT=1522
export OJDBC_DATABASE=AJOPA.world
export OJDBC_USERNAME=AJO
export OJDBC_PASSWORD=Uob12345
export OJDBC_SCHEMA=ajo
export SECUTIRY_REALM=Java Base
export KEYSTORE_PASSWORD=Welcome1!
export JWT_CLIENT_ID=adminapp
export JWT_CLIENT_SECRET=password
export JWT_RESOURCE_IDS=mw/adminapp
export APP_NAME=uob_ajo_backend
export APP_NAME_DESC=UOB Aplikasi Jaminan Online Backend API
export AUTHOR_NAME=ebiz cipta
export AUTHOR_EMAIL=tommi.munte@ebizcipta.com
export SERVER_PORT=8080
export ADMIN_PASSWORD=Welcome@1
export FTP_AS400_SERVER=10.1.1.5
export FTP_AS400_SERVER_PORT=23
export FTP_AS400_SERVER_USERNAME=ajoidoleu
export FTP_AS400_SERVER_PASSWORD=ajoidoleu$